name: Check Typst Release

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

jobs:
  check-and-create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Download last checked version
        uses: actions/download-artifact@v5
        with:
          name: last-typst-version
        continue-on-error: true

      - name: Check for new Typst release and create issue if found
        id: check_release
        run: |
          RELEASE_INFO_JSON=$(gh api "repos/typst/typst/releases/latest")
          LATEST_RELEASE=$(echo "$RELEASE_INFO_JSON" | jq -r .tag_name)
          RELEASE_URL=$(echo "$RELEASE_INFO_JSON" | jq -r .html_url)

          LAST_VERSION=$(cat last_checked_typst_version.txt 2>/dev/null || echo "")

          if [ "$LAST_VERSION" != "$LATEST_RELEASE" ]; then
            gh issue create \
              --title "New Typst release detected: $LATEST_RELEASE" \
              --body "A new release of Typst is available.\nSee the details here: [$LATEST_RELEASE]($RELEASE_URL)"
          fi
          echo "$LATEST_RELEASE" > last_checked_typst_version.txt

      - name: Upload new version file
        uses: actions/upload-artifact@v4
        with:
          name: last-typst-version
          path: last_checked_typst_version.txt
