name: Check Typst Release

on:
  schedule:
    - cron: "0 0 */5 * *" # Every 5 days
  workflow_dispatch:

jobs:
  check-and-create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v5
      - name: Restore last checked version from cache
        uses: actions/cache@v4
        with:
          path: last_checked_typst_version.txt
          key: last_checked_typst_version

      - name: Check for new Typst release and create issue if found
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_INFO_JSON=$(gh api "repos/typst/typst/releases/latest")
          LATEST_RELEASE=$(echo "$RELEASE_INFO_JSON" | jq -r .tag_name)
          RELEASE_URL=$(echo "$RELEASE_INFO_JSON" | jq -r .html_url)

          LAST_VERSION=$(cat last_checked_typst_version.txt 2>/dev/null || echo "")

          if [ "$LAST_VERSION" != "$LATEST_RELEASE" ]; then
            gh issue create \
              --title "New Typst release: $LATEST_RELEASE" \
              --body "A new release of Typst is available. See the details here: [$LATEST_RELEASE]($RELEASE_URL)"
          fi
          echo "$LATEST_RELEASE" > last_checked_typst_version.txt
